version: '3.8'
services:
  web:
    image: argum:local
    container_name: argum_web
    restart: always
    environment:
      - DB_HOST:db
      - DB_USER=root
      - DB_PASSWORD=example
    ports:
      - 3000:3000
    networks:
      - argum
    depends_on:
      - db
#   db:
#     image: mongo:5.0.22
#     restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: example
#     volumes:
#       - db-vol:/data/db
#   mongoku:
#     image: huggingface/mongoku:latest
#     container_name: mongoku
#     restart: on-failure
#     ports:
#       - 3100:3100
#     environment:
#       MONGOKU_DEFAULT_HOST: "mongodb://root:example@db:27017"
# volumes:
#   db-vol:
#     name: db-vol
networks:
  argum:
    name: argum